name: VanillaAFK
version: '1.2'
main: com.rimzzy.vanillaAFK.VanillaAFK
api-version: '1.21'
authors: [ Rimzzy ]
description: "AFK плагин с кастомными сообщениями и баблами над головой"

commands:
  afk:
    description: "Войти/выйти из AFK режима"
    usage: "/afk [текст]"
  afk-reload:
    description: "Перезагрузить конфигурацию плагина"
    usage: "/afk-reload"

permissions:
  vanillaafk.use:
    description: "Позволяет использовать команду /afk"
    default: true
  vanillaafk.customtext:
    description: "Позволяет использовать кастомный текст для AFK"
    default: op
  vanillaafk.reload:
    description: "Позволяет перезагружать конфигурацию плагина"
    default: op